### ISSUE TITLE
Fix Let's Encrypt Cert Auto Renewal

### ISSUE THREAD

**Issue by jasonrogena** [opensrp/playbooks#14]
_From @jasonrogena on February 5, 2018 13:59_

_From @jasonrogena on January 24, 2018 11:27_

Switch to using [certbot-auto](https://certbot.eff.org/all-instructions/) for renewing Let's Encrypt certs. Will involve:
 - [ ] Adding a task for downloading the certbot-auto binary.
 - [ ] Copying a renewal script to the server that stops NGINX, calls certbot-auto for renewal, copies the new certs from `/etc/letsencrypt/live` to `/etc/nginx/ssl` then starts NGINX.
 - [ ] [Creating a SystemD timer](https://nairobilug.or.ke/2016/07/using-systemd-timers-to-renew-lets-encrypt-certificates.html) that calls the renewal script weekly.

_Copied from original issue: OpenSRP/playbooks#40_

_Copied from original issue: onaio/playbooks-opensrp#1_

**Comment by jasonrogena** [comment]
If you make certbot-auto drop the challenge somewhere in Tomcat's ROOT web-app folder, it might lead to less downtime during auto-renewal. Will need us to change the nginx site files though (to allow for non-HTTPS traffic to the `/challenge` slug for instance then redirecting traffic to that slug to Tomcat7 ROOT web-app dir). Specify webroot using the `[--webroot](https://certbot.eff.org/docs/using.html#webroot)` flag.

It's also possible to use the `[--nginx](https://certbot.eff.org/docs/using.html#nginx)` flag with certbot-auto (0.9 and above).

**Comment by ndegwamartin** [comment]
@ukanga also , for the TB Reach server note that it hosts both the TB-Reach and Uganda Hpv domains, so the auto renewal set up needs to to factor that in. Perhaps we might have more in future (if we have a robust enough server for demo purposes) with multiple OpenSRP apps running side by side.

**Comment by ukanga** [comment]
I have updated the certbot role, I should look into integrating into the opensrp roles.

**Comment by jasonrogena** [comment]
@manutarus [Morris Mukiri](https://github.com/morrismukiri) made more updates to the certbot role to allow for auto-renewal. To get these changes you might have to point the git submodule to the [latest](https://github.com/onaio/ansible-certbot/commit/acfb96e49bc84280cc1bf0032437f8012421044b) commit.

```sh
git submodule update --remote roles/certbot
git add roles/certbot
git commit
```
