### ISSUE TITLE
Role for installing and setting up PostgreSQL 

### ISSUE THREAD

**Issue by keymane** [opensrp/playbooks#18]

**Comment by jasonrogena** [comment]
Would be nice to also think about [PgBouncer](https://pgbouncer.github.io/) that will make scaling out, running maintenance on the DBs much easier. We use [this](https://github.com/onaio/ansible-pgbouncer) role for PgBouncer, and [this](https://galaxy.ansible.com/ANXS/postgresql/) for PostgreSQL.
