### ISSUE TITLE
Add DB SSL support for on-site deployments

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/playbooks#206]
Support for generating and installing ssl certificates for SSL connection on DB instances

- [ ] Generate a CA key and certificate.
- [ ] Add cert to version control

Generate and sign SSL certs using the CA certificate using ansible role
https://github.com/onaio/ansible-ssl-certificate

**Comment by jasonrogena** [comment]
@ndegwamartin I think we can do this using the https://github.com/onaio/ansible-ssl-certificate role . Let me see what I can do since I need this fixed for a deployment I'm doing.

**Comment by ndegwamartin** [comment]
@jasonrogena any feedback on this?

**Comment by jasonrogena** [comment]
No feedback yet. Something came up before I could implement the change.

**Comment by jasonrogena** [comment]
Fixed by https://github.com/OpenSRP/playbooks/pull/222
