### ISSUE TITLE
Nginx Role

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/playbooks#6]
Use [this](https://galaxy.ansible.com/geerlingguy/nginx/) Ansible Galaxy Nginx role instead of maintaining our own.

**EDIT (8th January 2018):**
Switch to using [Ona's NGINX role](https://github.com/onaio/ansible-nginx).

**Comment by pld** [comment]
Is that the starriest one?

**Comment by jasonrogena** [comment]
@pld Yeah, I guess. 95844 galaxy downloads, vs 36082 for the second most popular I could find https://galaxy.ansible.com/jdauphant/nginx/

**Comment by jasonrogena** [comment]
This issue was moved to onaio/playbooks-opensrp#9
