### ISSUE TITLE
Use Ona's Nginx Role

### ISSUE THREAD

**Issue by jasonrogena** [opensrp/playbooks#6]
Use Ona's much more robust NGINX role.
 
_Copied from original issue: OpenSRP/playbooks#6_

_Copied from original issue: onaio/playbooks-opensrp#9_

**Comment by jasonrogena** [comment]
_From @pld on October 10, 2017 13:26_

Is that the starriest one?

**Comment by jasonrogena** [comment]
@pld Yeah, I guess. 95844 galaxy downloads, vs 36082 for the second most popular I could find https://galaxy.ansible.com/jdauphant/nginx/

**Comment by pld** [comment]
cool, we've already committed w/our own forked repo so cool

**Comment by jasonrogena** [comment]
Yeah. Old issue. Gonna rename this to "Use Ona's NGINX role".
