### ISSUE TITLE
Implement Log rotation for OpenSRP and OpenMRS tomcat instances

### ISSUE THREAD

**Issue by githengi** [opensrp/playbooks#60]
Tomcat logs sometimes grow to very huge sizes reducing the performance on tomcat.

- [x] Implement Log rotation for OpenSRP and OpenMRS tomcat instance.

- [x] The rotation policy should be configurable by  
      - Date/Daily
      - Size of log file
      - Number or log files to maintain.

- [x] The rotated files should be compressed

**Comment by manutarus** [comment]
Tomcat already implements log rotation, however catalina.out is not rotated and we may need to find away to rotate this

**Comment by hngondoki** [comment]
@jasonrogena @manutarus Logrotate is causing an upsurge of resource utilization in the OpenSRP servers. Please help look into the issue... e.g. anc-uat-smartregister-org server

**Comment by jasonrogena** [comment]
@hmakandi that issue was fixed by https://github.com/OpenSRP/playbooks/commit/32046f0a7f92f5466f180856623bfea12989a8fb . Redeploying the affected application should fix it. You might also want to recreate the directory storing the logs (most likely `/home/opensrp/tomcat-opensrp/logs`)

**Comment by jasonrogena** [comment]
@hmakandi @morrismukiri just fixed a bug in the logrotate file changes in https://github.com/OpenSRP/playbooks/commit/32046f0a7f92f5466f180856623bfea12989a8fb that was causing rotation not to work.
