### ISSUE TITLE
Add Support for enabling POSTGIS extension

### ISSUE THREAD

**Issue by githengi** [opensrp/playbooks#69]
Add Support for enabling POSTGIS extension in the OpenSRP postgres database.

The database maybe running on RDS or as a normal PostgreSQL database.

This is required for reveal deployments for the purpose of querying structures with a distance from some co-ordinates.

Required by [https://github.com/OpenSRP/opensrp-server-web/issues/42](https://github.com/OpenSRP/opensrp-server-web/issues/42)

**Comment by jasonrogena** [comment]
The PostregSQL role supports defining variables to enable PostGIS
